version: '3.8'

services:
  database:
    image: postgres:14
    container_name: red_social_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: red_social_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redsocialnet

  backend:
    build:
      context: ./backend
    container_name: red_social_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:admin123@database:5432/red_social_db"
      JWT_SECRET: "clave_secreta_segura"
    depends_on:
      - database
    networks:
      - redsocialnet

  frontend:
    build:
      context: ./frontend
    container_name: red_social_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"
    depends_on:
      - backend
    networks:
      - redsocialnet

volumes:
  postgres_data:

networks:
  redsocialnet:
    driver: bridge
